# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='priority',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
    ]
