# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 06:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_auto_20180922_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='dateConcerned',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 6, 38, 52, 567605, tzinfo=utc), verbose_name='event Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklist',
            name='timeCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
