# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_auto_20180922_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='isDeleted',
        ),
    ]
