# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0005_remove_checklist_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
